/**
 * Sub: Constructors
 * 
 * There are different approaches to create objects...
 * i. new Keyword,
 * ii. Instance factory method,
 * iii. Static factory method,
 * iv. Pattern factory method,
 * v. new Instance() method,
 * vi. clone() method,
 * vii. De-serialization process,
 * 
 * Test t = new Test();
 * 
 * Test ---> class name,
 * t    ---> reference-variable(object name)
 * new  ---> keyword (used to create object)
 * Test() --> Constructor
 * 
 * Note-1:
 * Every time when we create the object during the object creation the
 * constructor will be executed.
 * 
 * Rules to declare constructors in Java
 * --------------------------------------
 * 1. Constructor name and class name must be same.
 * 2. Constructor able to take parameters
 * 3. Constructor not allowed return types,
 *
 *Default Constructor (OR) Zero Argument Constructor
 *--------------------------------------------------- 
 * If we are not declare constructors in a class, compiler will generate a
 * zero argument constructor. It also called as 'Default Constructor'
 * 
 * Types of Constructor
 * --------------------
 * There are 2-types of constructors...
 * i. Default Constructor - 
 *    a. It is generated by compiler,
 *    b. It is always ZERO_ARGUMENT Constructor,
 *    c. This constructor should have 'empty implementation'
 * ii. User-defined Constructor - 
 *    a. It is created by user.
 *    b. Based on user requirements user can create it with ZERO_ARGUMENT Constructor,
 *    c. Here it is possible to pass the parameters in the user-defined constructor.
 * 
 */


package com.constructor;

public class TheoryOnConstructor {

}
